set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Enable RGB colour if running in xterm(1)
set-option -sa terminal-overrides ",xterm*:Tc"

# Enable image rendering for yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

