require 'plugins.lazy'
require 'plugins.plugins'
require 'core.keymaps'
require 'core.settings'
require 'codeExec.debugger'
require 'codeExec.coderunner'
require 'custom.keymaps.harpoon'
-- require 'custom.formatting.format'
